# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  encoding: unicode
  reconnect: true
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  # ieg_events_production
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 20 } %>

development:
  <<: *default
  adapter: postgresql
  database: maps_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  adapter: postgresql
  database: maps_test
  username: postgres
  password: postgres
  host: localhost  